/*
 * generated by Xtext 2.15.0
 */
package xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import xtext.DatamodelsRuntimeModule
import xtext.DatamodelsStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DatamodelsIdeSetup extends DatamodelsStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DatamodelsRuntimeModule, new DatamodelsIdeModule))
	}
	
}
