/*
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DatamodelsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uam/mde20/sqlsi/xtext/parser/antlr/internal/InternalDatamodels.tokens");
	}
}
