/*
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uam.mde20.sqlsi.xtext.parser.antlr.internal.InternalDatamodelsParser;
import uam.mde20.sqlsi.xtext.services.DatamodelsGrammarAccess;

public class DatamodelsParser extends AbstractAntlrParser {

	@Inject
	private DatamodelsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDatamodelsParser createParser(XtextTokenStream stream) {
		return new InternalDatamodelsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DataModel";
	}

	public DatamodelsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DatamodelsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
