/*
 * generated by Xtext 2.15.0
 */
package xtext.datamodels.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDatamodelsScopeProvider extends DelegatingScopeProvider {
}
