/**
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext;

import uam.mde20.sqlsi.xtext.AbstractSecuritymodelsRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SecuritymodelsRuntimeModule extends AbstractSecuritymodelsRuntimeModule {
}
