/*
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DatamodelsStandaloneSetup extends DatamodelsStandaloneSetupGenerated {

	def static void doSetup() {
		new DatamodelsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
