/**
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext.ui.contentassist;

import uam.mde20.sqlsi.xtext.ui.contentassist.AbstractSecuritymodelsProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SecuritymodelsProposalProvider extends AbstractSecuritymodelsProposalProvider {
}
