/**
 * generated by Xtext 2.15.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import xtext.ui.AbstractDatamodelsUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DatamodelsUiModule extends AbstractDatamodelsUiModule {
  public DatamodelsUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
