/*
 * generated by Xtext 2.15.0
 */
package xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.securitymodels.ui.internal.SecuritymodelsActivator;

public class SecuritymodelsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SecuritymodelsActivator.getInstance().getInjector("xtext.Securitymodels");
	}

}
