/*
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SecuritymodelsRuntimeModule extends AbstractSecuritymodelsRuntimeModule {
}
