/**
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels;

import xtext.securitymodels.AbstractSecurityModelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SecurityModelRuntimeModule extends AbstractSecurityModelRuntimeModule {
}
