/**
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels;

import xtext.securitymodels.SecurityModelStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SecurityModelStandaloneSetup extends SecurityModelStandaloneSetupGenerated {
  public static void doSetup() {
    new SecurityModelStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
