/*
 * generated by Xtext 2.15.0
 */
package xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.datamodels.ui.internal.DatamodelsActivator;

public class DatamodelsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DatamodelsActivator.getInstance().getInjector("xtext.Datamodels");
	}

}
