/*
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uam.mde20.sqlsi.xtext.securitymodels.ui.internal.SecuritymodelsActivator;

public class SecuritymodelsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SecuritymodelsActivator.getInstance().getInjector("uam.mde20.sqlsi.xtext.Securitymodels");
	}

}
