/*
 * generated by Xtext 2.15.0
 */
package xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SecuritymodelsStandaloneSetup extends SecuritymodelsStandaloneSetupGenerated {

	def static void doSetup() {
		new SecuritymodelsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
