/**
 * generated by Xtext 2.15.0
 */
package xtext.datamodels.validation;

import xtext.datamodels.validation.AbstractDatamodelsValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DatamodelsValidator extends AbstractDatamodelsValidator {
}
