/*
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSecurityModelScopeProvider extends DelegatingScopeProvider {
}
