/**
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext.ide;

import uam.mde20.sqlsi.xtext.ide.AbstractSecuritymodelsIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SecuritymodelsIdeModule extends AbstractSecuritymodelsIdeModule {
}
