/**
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uam.mde20.sqlsi.xtext.SecuritymodelsRuntimeModule;
import uam.mde20.sqlsi.xtext.SecuritymodelsStandaloneSetup;
import uam.mde20.sqlsi.xtext.ide.SecuritymodelsIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SecuritymodelsIdeSetup extends SecuritymodelsStandaloneSetup {
  @Override
  public Injector createInjector() {
    SecuritymodelsRuntimeModule _securitymodelsRuntimeModule = new SecuritymodelsRuntimeModule();
    SecuritymodelsIdeModule _securitymodelsIdeModule = new SecuritymodelsIdeModule();
    return Guice.createInjector(Modules2.mixin(_securitymodelsRuntimeModule, _securitymodelsIdeModule));
  }
}
