/*
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.securitymodels.editor.ui.internal.EditorActivator;

public class SecurityModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EditorActivator.getInstance().getInjector("xtext.securitymodels.SecurityModel");
	}

}
