/*
 * generated by Xtext 2.15.0
 */
package xtext.datamodels.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DatamodelsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("xtext/datamodels/parser/antlr/internal/InternalDatamodels.tokens");
	}
}
