/**
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels.ui.contentassist;

import xtext.securitymodels.ui.contentassist.AbstractSecurityModelProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SecurityModelProposalProvider extends AbstractSecurityModelProposalProvider {
}
