/**
 * generated by Xtext 2.15.0
 */
package xtext;

import xtext.DatamodelsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DatamodelsStandaloneSetup extends DatamodelsStandaloneSetupGenerated {
  public static void doSetup() {
    new DatamodelsStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
