/**
 * generated by Xtext 2.15.0
 */
package xtext;

import xtext.SecuritymodelsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SecuritymodelsStandaloneSetup extends SecuritymodelsStandaloneSetupGenerated {
  public static void doSetup() {
    new SecuritymodelsStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
