/**
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import xtext.securitymodels.ui.AbstractSecurityModelUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SecurityModelUiModule extends AbstractSecurityModelUiModule {
  public SecurityModelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
