/*
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDatamodelsScopeProvider extends DelegatingScopeProvider {
}
