/**
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext.validation;

import uam.mde20.sqlsi.xtext.validation.AbstractDatamodelsValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DatamodelsValidator extends AbstractDatamodelsValidator {
}
