/*
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SecurityModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("xtext/securitymodels/parser/antlr/internal/InternalSecurityModel.tokens");
	}
}
