/**
 * generated by Xtext 2.15.0
 */
package xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.DatamodelsRuntimeModule;
import xtext.DatamodelsStandaloneSetup;
import xtext.ide.DatamodelsIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DatamodelsIdeSetup extends DatamodelsStandaloneSetup {
  @Override
  public Injector createInjector() {
    DatamodelsRuntimeModule _datamodelsRuntimeModule = new DatamodelsRuntimeModule();
    DatamodelsIdeModule _datamodelsIdeModule = new DatamodelsIdeModule();
    return Guice.createInjector(Modules2.mixin(_datamodelsRuntimeModule, _datamodelsIdeModule));
  }
}
