/**
 * generated by Xtext 2.15.0
 */
package xtext.ide;

import xtext.ide.AbstractDatamodelsIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DatamodelsIdeModule extends AbstractDatamodelsIdeModule {
}
