/**
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels.ide;

import xtext.securitymodels.ide.AbstractSecurityModelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SecurityModelIdeModule extends AbstractSecurityModelIdeModule {
}
