/**
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtext.securitymodels.SecurityModelRuntimeModule;
import xtext.securitymodels.SecurityModelStandaloneSetup;
import xtext.securitymodels.ide.SecurityModelIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SecurityModelIdeSetup extends SecurityModelStandaloneSetup {
  @Override
  public Injector createInjector() {
    SecurityModelRuntimeModule _securityModelRuntimeModule = new SecurityModelRuntimeModule();
    SecurityModelIdeModule _securityModelIdeModule = new SecurityModelIdeModule();
    return Guice.createInjector(Modules2.mixin(_securityModelRuntimeModule, _securityModelIdeModule));
  }
}
