/*
 * generated by Xtext 2.15.0
 */
package uam.mde20.sqlsi.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import uam.mde20.sqlsi.xtext.datamodels.ui.internal.DatamodelsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DatamodelsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DatamodelsActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DatamodelsActivator activator = DatamodelsActivator.getInstance();
		return activator != null ? activator.getInjector(DatamodelsActivator.UAM_MDE20_SQLSI_XTEXT_DATAMODELS) : null;
	}

}
