/**
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels.validation;

import xtext.securitymodels.validation.AbstractSecurityModelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SecurityModelValidator extends AbstractSecurityModelValidator {
}
