/*
 * generated by Xtext 2.15.0
 */
package xtext.securitymodels


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SecurityModelStandaloneSetup extends SecurityModelStandaloneSetupGenerated {

	def static void doSetup() {
		new SecurityModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
